densification_interval: 100
densify_from_iter: 0
densify_grad_threshold: 0.0002
densify_until_iter: 0
dist_reg_from: 0
estimate_normals: 1
fast_init: 0
feature_lr: 0.0025
gaussians_init: 2dgs
iterations: 1000
lambda_dist: 0.0
lambda_dssim: 0.2
lambda_normal: 0.01
matches_per_ref: 15000
nns_per_ref: 3
normal_estimate_knn: 20
normal_reg_from: 0
old_init: 1
opacity_cull: 0.005
opacity_lr: 0.025
opacity_reset_interval: 30000
percent_dense: 0.01
position_lr_delay_mult: 0.01
position_lr_final: 1.6e-06
position_lr_init: 1.6e-05
position_lr_max_steps: 30000
proj_err_tolerance: 0.01
roma_model: Indoor
rotation_lr: 0.001
scaling_factor: 0.001
scaling_lr: 0.005
